# Generated by Django 5.2.7 on 2025-10-21 14:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('host', 'Host'), ('technician', 'Technician'), ('supervisor', 'Supervisor')], default='technician', help_text='User role in the system', max_length=20)),
                ('city', models.CharField(blank=True, help_text='City assignment (NULL for host/supervisor)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(help_text='Unique device identifier', max_length=50, unique=True)),
                ('gfm_cost_center', models.CharField(help_text='Cost center information', max_length=100)),
                ('region', models.CharField(help_text='Device location region (populated from Excel Status column)', max_length=100)),
                ('gfm_problem_type', models.CharField(help_text='Problem classification', max_length=100)),
                ('gfm_problem_date', models.DateField(help_text='Problem report date')),
                ('city', models.CharField(help_text='Device location city', max_length=100)),
                ('type', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Electrical', 'Electrical')], help_text='Maintenance type', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device',
                'indexes': [models.Index(fields=['city'], name='device_city_1e6bce_idx'), models.Index(fields=['type'], name='device_type_7f6892_idx'), models.Index(fields=['city', 'type'], name='device_city_79b285_idx')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Electrical', 'Electrical')], help_text='Maintenance type', max_length=20)),
                ('visit_date', models.DateField(help_text='Date of maintenance visit')),
                ('half_month', models.IntegerField(help_text='Half-month period (1 or 2)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status', max_length=20)),
                ('pdf_url', models.URLField(blank=True, help_text='Generated PDF report URL', max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Supervisor remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Target device', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.device')),
                ('technician', models.ForeignKey(help_text='Submitting technician', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(help_text='Photo section (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('file_url', models.URLField(help_text='Photo file URL', max_length=500)),
                ('order_index', models.IntegerField(help_text='Photo order within section')),
                ('submission', models.ForeignKey(help_text='Parent submission', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.submission')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='TechnicianDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(help_text='Reference to device', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technicians', to='core.device')),
                ('technician', models.ForeignKey(help_text='Reference to technician', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_device',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_3744fd_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submission_status_81973f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submission_created_152927_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='submission_status_7ca9c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('device', 'half_month')},
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['submission'], name='photo_submiss_dda9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['submission', 'section'], name='photo_submiss_f047ba_idx'),
        ),
        migrations.AddIndex(
            model_name='techniciandevice',
            index=models.Index(fields=['technician'], name='technician__technic_f6301f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='techniciandevice',
            unique_together={('technician', 'device')},
        ),
    ]
