# Generated by Django 5.2.7 on 2025-10-23 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original Excel file name', max_length=255)),
                ('file_path', models.CharField(help_text='Path to stored Excel file', max_length=500)),
                ('device_type', models.CharField(blank=True, choices=[('Cleaning', 'Cleaning'), ('Electrical', 'Electrical')], help_text='Device type for this upload', max_length=20, null=True)),
                ('parsed_data', models.JSONField(help_text='Parsed Excel data stored as JSON')),
                ('row_count', models.IntegerField(default=0, help_text='Number of rows in Excel file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('technician', models.ForeignKey(help_text='Technician who owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='Host user who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'excel_upload',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['technician'], name='excel_uploa_technic_0fb07f_idx'), models.Index(fields=['upload_date'], name='excel_uploa_upload__83f6c8_idx')],
            },
        ),
    ]
