# Generated by Django 5.2.7 on 2025-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_excelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gfm_problem_date',
            field=models.CharField(blank=True, help_text='Problem report date or description', max_length=100, null=True),
        ),
    ]
