# Generated by Django 5.2.7 on 2025-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_device_gfm_problem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='job_status',
            field=models.CharField(choices=[('Ok', 'Ok'), ('Not Ok', 'Not Ok')], default='Ok', help_text='Job completion status (Ok/Not Ok)', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status (Pending/Approved/Rejected)', max_length=20),
        ),
    ]
