# Generated by Django 5.2.7 on 2025-11-07 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_replace_unique_constraint_for_resubmission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submission_technic_1ae352_idx',
            old_name='submission_technician_device_idx',
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='device_type',
            field=models.CharField(blank=True, choices=[('Cleaning1', 'Cleaning1'), ('Cleaning2', 'Cleaning2'), ('Electrical', 'Electrical'), ('Security', 'Security'), ('Stand Alone', 'Stand Alone')], help_text='Device type for this upload', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='section',
            field=models.IntegerField(help_text='Photo section (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('Cleaning1', 'Cleaning1'), ('Cleaning2', 'Cleaning2'), ('Electrical', 'Electrical'), ('Security', 'Security'), ('Stand Alone', 'Stand Alone')], help_text='Maintenance type', max_length=20),
        ),
    ]
